(module constants racket
  (provide (all-defined-out))
  (require ffi/unsafe
           ffi/unsafe/define)
         
  (define NSOpenGLPFAAllRenderers         1)
  (define NSOpenGLPFADoubleBuffer         5)
  (define NSOpenGLPFAStereo               6)
  (define NSOpenGLPFAAuxBuffers           7)
  (define NSOpenGLPFAColorSize            8)
  (define NSOpenGLPFAAlphaSize           11)
  (define NSOpenGLPFADepthSize           12)
  (define NSOpenGLPFAStencilSize         13)
  (define NSOpenGLPFAAccumSize           14)
  (define NSOpenGLPFAMinimumPolicy       51)
  (define NSOpenGLPFAMaximumPolicy       52)
  (define NSOpenGLPFAOffScreen           53)
  (define NSOpenGLPFAFullScreen          54)
  (define NSOpenGLPFASampleBuffers       55)
  (define NSOpenGLPFASamples             56)
  (define NSOpenGLPFAAuxDepthStencil     57)
  (define NSOpenGLPFAColorFloat          58)
  (define NSOpenGLPFAMultisample         59)
  (define NSOpenGLPFASupersample         60)
  (define NSOpenGLPFASampleAlpha         61)
  (define NSOpenGLPFARendererID          70)
  (define NSOpenGLPFASingleRenderer      71)
  (define NSOpenGLPFANoRecovery          72)
  (define NSOpenGLPFAAccelerated         73)
  (define NSOpenGLPFAClosestPolicy       74)
  (define NSOpenGLPFARobust              75)
  (define NSOpenGLPFABackingStore        76)
  (define NSOpenGLPFAMPSafe              78)
  (define NSOpenGLPFAWindow              80)
  (define NSOpenGLPFAMultiScreen         81)
  (define NSOpenGLPFACompliant           83)
  (define NSOpenGLPFAScreenMask          84)
  (define NSOpenGLPFAPixelBuffer         90)
  (define NSOpenGLPFARemotePixelBuffer   91)
  (define NSOpenGLPFAAllowOfflineRenderers 96)
  (define NSOpenGLPFAAcceleratedCompute  97)
  (define NSOpenGLPFAVirtualScreenCount 128)

  (define (array #:type type . elements)
    (define size (length elements))
    (define result
      (ptr-ref (malloc type size 'atomic)
               (_array type size)))
    (for ([i (in-range 0 size)]
          [val (in-list elements)])
      (array-set! result i val))
    result)
    
    
    
)
